version: 1
agent:
  extend: default
  name: security
  system_prompt_path: ./security.md
  exclude_tools:
    - "kimi_cli.tools.shell:Shell"
    - "kimi_cli.tools.file:WriteFile"
    - "kimi_cli.tools.file:StrReplaceFile"
    - "kimi_cli.tools.todo:SetTodoList"
    - "kimi_cli.tools.multiagent:CreateSubagent"
    - "kimi_cli.tools.multiagent:Task"
